# Generated by Django 3.0.6 on 2021-10-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genApp', '0003_teacheravaiablehour'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='avaiable_hours',
            field=models.ManyToManyField(related_name='teacher_model', to='genApp.TeacherAvaiableHour'),
        ),
    ]
