# Generated by Django 3.0.6 on 2021-10-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genApp', '0004_teachermodel_avaiable_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='avaiable_hours',
            field=models.ManyToManyField(related_name='class_model', to='genApp.TeacherAvaiableHour'),
        ),
    ]
