# Generated by Django 3.0.6 on 2021-10-20 08:05

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genApp', '0005_classmodel_avaiable_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmodel',
            name='schedule_json',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
