# Generated by Django 3.0.6 on 2021-10-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genApp', '0006_schoolmodel_schedule_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmodel',
            name='schedule_json',
            field=models.CharField(max_length=9000000000000),
        ),
    ]
